export const cardsData = [
  {
    title: 'Mini',
    price: '€150',
    description: 'For short sessions and quick results',
    confirmBtn: 'Book Now',
    details: [
      'Up to 1 hour of shooting',
      '1 outfit / 1 location',
      '20 edited photos',
      'Online gallery',
      'Delivery within 7 days',
    ],
  },

  {
    title: 'Classic',
    price: '€280',
    description: 'Perfect for couples, portraits, or lifestyle',
    confirmBtn: 'Book Now',
    details: [
      'Up to 2 hours of shooting',
      '2 outfits / 2 locations',
      '40+ edited photos',
      'Online gallery',
      'Pre-shoot consultation',
      'Posing guidance',
      'Delivery within 10 days',
    ],
  },
  {
    title: 'Story',
    price: '€450',
    description: 'For when you want to capture everything',
    confirmBtn: 'Book Now',
    details: [
      'Up to 4 hours of shooting',
      '3–4 outfits and locations',
      '80+ edited photos',
      'Online gallery + backup link',
      'Custom route planning',
      'Moodboard and styling help',
      'Includes breaks and travel time',
      'Delivery within 14 days',
    ],
  },
  {
    title: 'Wedding',
    price: '€900',
    description: 'Full-day or partial wedding coverage',
    confirmBtn: 'Book Now',
    details: [
      'Up to 8 hours of shooting',
      'All key moments covered',
      '250+ artistically edited photos',
      'Custom timeline planning',
      'Online gallery + USB drive',
      'Delivery within 21 days',
      'Extras: photo album, prints',
      'Optional second-day shoot',
    ],
  },
];
